config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  devise_for :users

  resources :plant_seeds, path: 'seeds'
  resources :maps

end

app/models/building.rb
class Building
  include ActiveModel::Model

  attr_accessor :id, :name # ...

  validates :name, presence: true

  ALL = []

  def self.count
    ALL.size
  end

end

app/models/map.rb
class Map < ActiveRecord::Base
  belongs_to :user

  before_validation :nilify_blanks

  scope :most_recent, -> { order('maps.updated_at') }

  def plant_seeds
    PlantSeed.all
  end

  def unacquired_plant_seeds
    PlantSeed.all.reject { |ps| has_seed? ps }
  end

  def acquired_plant_seeds
    PlantSeed.all.select { |ps| has_seed? ps }
  end

  def has_seed?(seed)
    acquired_seeds.include?(seed.id)
  end

  private
  def nilify_blanks
    self.name = nil if self.name.blank?
  end
end

app/models/plant_seed.rb
class PlantSeed
  include ActiveModel::Model

  attr_accessor :id, :name, :plant_type, :from_mod_id, :product,
    :maturation_speed, :frost_resistance

  MODS = {
    1 => 'Vanilla Banished',
    2 => 'Colonial Charter',
  }.freeze
  MOD_OPTIONS = MODS.invert.freeze

  validates :product, presence: true
  validates :plant_type,  inclusion: { in: %w[ crop orchard ] }
  validates :from_mod_id, inclusion: { in: MODS.keys }

  validates :name, presence: true

  ALL = []

  data_file = File.expand_path('../plant_seeds.json', __FILE__)
  JSON::parse(File.read(data_file)).tap do |json|
    json['plant_seeds'].each do |data|
      data['product'] = Product.find_by_name(data.delete('product_name'))
      plant_seed = PlantSeed.new(data)
      raise 'Invalid PlantSeed' unless plant_seed.valid?
      ALL << plant_seed
    end
  end

  def orchard?
    plant_type == 'orchard'
  end

  def self.all
    ALL
  end

  def self.count
    all.size
  end

  def to_s
    name
  end

end

app/models/product.rb
class Product
  include ActiveModel::Model

  attr_accessor :id, :name

  def self.build(id, name)
    Product.new(id: id, name: name)
  end

  ALL = [
    build( 1, 'Ale'),
    build( 2, 'Cloth'),
    build( 3, 'Fire Bundle'),
    build( 4, 'Flour'),
    build( 5, 'Fruit Bread'),
    build( 6, 'Linen'),
    build( 7, 'Liquor'),
    build( 8, 'Maple Sap'),
    build( 9, 'Nut Bread'),
    build(10, 'Oil'),
    build(11, 'Pipe Tobacco'),
    build(12, 'Rope'),
    build(13, 'Silkworms'),
    build(14, 'Sugar'),
    build(15, 'Wine'),
    build(16, 'Apples'),
    build(17, 'Apricots'),
    build(18, 'Bamboo'),
    build(19, 'Barley'),
    build(20, 'Beans'),
    build(21, 'Beetroots'),
    build(22, 'Blackberries'),
    build(23, 'Blueberries'),
    build(24, 'Brocolli'),
    build(25, 'Cabbage'),
    build(26, 'Carrots'),
    build(27, 'Cherries'),
    build(28, 'Chestnuts'),
    build(29, 'Chickpeas'),
    build(30, 'Corn'),
    build(31, 'Cotton'),
    build(32, 'Cucumbers'),
    build(33, 'Figs'),
    build(34, 'Flax'),
    build(35, 'Grapes'),
    build(36, 'Hemp'),
    build(37, 'Kale'),
    build(38, 'Kernels'),
    build(39, 'Lettuce'),
    build(40, 'Maple Sap'),
    build(41, 'Olives'),
    build(42, 'Parsnips'),
    build(43, 'Peaches'),
    build(44, 'Pears'),
    build(45, 'Peas'),
    build(46, 'Pecans'),
    build(47, 'Peppers'),
    build(48, 'Plums'),
    build(49, 'Potatoes'),
    build(50, 'Pumpkins'),
    build(51, 'Quinces'),
    build(52, 'Radishes'),
    build(53, 'Raspberries'),
    build(54, 'Red Mulberries'),
    build(55, 'Sorghum'),
    build(56, 'Soybeans'),
    build(57, 'Spinach'),
    build(58, 'Squash'),
    build(59, 'Strawberries'),
    build(60, 'Sugar Cane'),
    build(61, 'Tobacco Leaf'),
    build(62, 'Tomatoes'),
    build(63, 'Turnips'),
    build(64, 'Walnuts'),
    build(65, 'Watermelons'),
    build(66, 'Wheat'),
    build(67, 'White Mulberry Leaves'),
    build(68, 'Maple Syrup'),
  ].freeze

  def self.count
    ALL.size
  end

  def self.find_by_name(name)
    ALL.detect { |p| p.name.downcase == name.to_s.downcase }
  end

  def self.find_by_name!(name)
    find_by_name(name) or raise "Record not found for #{name}"
  end

  def consumed_in
    Production.consuming(self)
  end

  def used_for
    consumed_in.map(&:outputs).flatten
  end

  def to_s
    name
  end
end

app/models/production.rb
class Production
  include ActiveModel::Model

  attr_accessor :id, :inputs, :outputs, :building

  validates :id, :outputs, presence: true

  ALL = []

  data_file = File.expand_path('../productions.json', __FILE__)
  JSON::parse(File.read(data_file)).tap do |json|
    json['production_maps'].each do |data|
      outputs = data['outputs'].map { |name|
        Product.find_by_name!(name)
      }

      data['input_options'].each do |input|
        inputs = input['inputs'].map { |name|
          Product.find_by_name!(name)
        }

        ALL << Production.new(
                          id: input['id'],
                      inputs: inputs.freeze,
                     outputs: outputs.dup.freeze)
      end
    end
  end

  def self.consuming(product)
    ALL.select { |p| p.inputs.include?(product) }
  end

  def self.producing(product)
    ALL.select { |p| p.outputs.include?(product) }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :maps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  before_action :find_map, except: [ :index, :new, :create ]

  def index
    @maps = current_user.maps.most_recent
  end

  def show
  end

  def new
    @map = Map.new
  end

  def create
    @map = current_user.maps.build(permitted_params)
    if @map.save
      redirect_to @map
    else
      render action: :new
    end
  end

  def update
    if @map.update(permitted_params)
      redirect_to @map
    else
      render action: :show
    end
  end

  def destroy
    @map.destroy
    redirect_to action: :index
  end

  private

  def find_map
    @map = current_user.maps.find(params[:id])
  end

  def permitted_params
    params.require(:map).permit(
      :name, acquired_seeds: [])
  end

end

app/controllers/plant_seeds_controller.rb
class PlantSeedsController < ApplicationController
  def index
    @plant_seeds = PlantSeed.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Banishedhq
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body

    %nav.top-bar{"data-topbar" => "", "data-options" => "is_hover: false", 'role' => 'navigation'}
      %ul.title-area
        %li.name
          %h1
            %a{:href => "/"}
              Banished HQ
        %li.toggle-topbar.menu-icon
          %a{:href => "#"}
            %span menu
      %section.top-bar-section
        %ul.right
          - if current_user
            %li= link_to('Maps', maps_path)
          %li.has-dropdown
            %a{:href => "#"} Account
            %ul.dropdown
              - if current_user
                %li= link_to('Sign Out', destroy_user_session_path)
              - else
                %li= link_to('Sign In', new_user_session_path)
                %li= link_to('Register', new_user_registration_path)

    .row
      .large-12.columns
        %p.notice= notice
        %p.alert= alert

    .row
      .large-12.columns
        = yield

    %footer.row
      .large-12.columns
        %hr/
        .row
          .large-6.columns
            %p © 2015 Copyright Darren Boyd.

          .large-6.columns
            %ul
              %li= link_to('About Me', '//darrenboyd.github.io/')

app/views/maps/_show_plant_seed.html.haml
.plant-seed{class: @map.has_seed?(seed) ? 'acquired' : 'not-acquired'}
  .row
    .columns.small-6
      %label.switch.radius
        = check_box_tag 'map[acquired_seeds][]', seed.id, @map.has_seed?(seed), id: "map_acquired_seeds_#{seed.id}"
        %label{for: "map_acquired_seeds_#{seed.id}"}
        = fa_icon(seed.orchard? ? 'tree' : 'leaf', class: 'fa-sm')
        = seed.name

    .columns.small-6
      .used-in
        = seed.product.used_for.map(&:name).join(', ')

app/views/maps/index.html.haml
.row
  .columns.small-12.large-8
    %h2 Your Maps
  .columns.small-12.large-4
    = link_to('New Map', new_map_path, class: 'button right')

- if @maps.any?
  - @maps.each do |map|
    %p= link_to(map.name || 'unnamed map', map)

- else
  %p
    You have no maps started yet, create one to manage all the things.

app/views/maps/new.html.haml
%h2 Add a Map

.row
  .columns.small-12.large-6
    = form_for @map do |f|
      = f.label :name
      = f.text_field :name
      = f.submit
      = link_to('cancel', maps_path)

app/views/maps/show.html.haml
%h2= best_in_place @map, :name, nil: 'unnamed map'

#map
  = form_for(@map) do |f|
    .row
      .columns.small-12
        = f.submit('Save Seeds', class: 'button right')

    %h3 Seeds To Acquire
    = render partial: 'show_plant_seed', collection: @map.unacquired_plant_seeds, as: :seed
    %h3 Acquired Seeds
    = render partial: 'show_plant_seed', collection: @map.acquired_plant_seeds, as: :seed

    .row
      .columns.small-12
        = f.submit('Save Seeds', class: 'button tiny')
  .row
    .columns.small-12
      = link_to('delete map', map_path(@map), method: :delete, class: 'right', data: { confirm: 'Are you sure?' })

app/views/plant_seeds/index.html.haml
%table
  - @plant_seeds.each do |seed|
    %tr
      %td= seed
      %td= seed.product
      %td= seed.product.used_for.map(&:to_s).join(', ')

app/views/welcome/index.html.haml
%h1 Welcome to Banished HQ
- if current_user
  %p Hi
- else
  %p= link_to('Sign In', new_user_session_path)
  %p= link_to('Register', new_user_registration_path)